/* =====================================================================
   data.js  —  Fair ford  B2B Pharma Marketplace
   ---------------------------------------------------------------------
   Single source of truth for product data.

   BACKEND-READY NOTE:
   This array mimics the JSON shape your Node.js + Express + MongoDB API
   should return from GET /api/products  and  GET /api/products/:id.
   To go live, replace `getAllProducts()` / `getProductById()` with
   `fetch()` calls — every consumer in products.js & product-details.js
   already reads through these two accessor functions, so the UI will
   not need to change.

       async function getAllProducts() {
         const res = await fetch('/api/products');
         return res.json();
       }

   Each product object maps 1:1 to a Mongoose document.
   ===================================================================== */

const PRODUCTS = [
  {
    id: "med-001",
    name: "Paracip 500 Tablets",
    brand: "Cipla",
    category: "Tablets",
    strength: "500 mg",
    packSize: "10 x 10 Tablets",
    mrp: 30.0,
    retailerPrice: 21.5,
    distributorPrice: 18.75,
    gst: 12,
    moq: 50,
    stock: 4200,
    stockStatus: "In Stock",
    rating: 4.6,
    reviewCount: 312,
    mfgDate: "2025-03",
    expDate: "2028-02",
    dosageForm: "Oral Tablet",
    composition: ["Paracetamol IP 500 mg", "Excipients q.s."],
    uses: "Used to relieve mild to moderate pain such as headache, toothache, body ache and to reduce fever.",
    benefits: ["Fast Relief", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Nausea", "Headache", "Dizziness", "Skin rash (rare)"],
    storage: ["Store below 25°C", "Keep away from direct sunlight", "Keep out of reach of children"],
    distributor: { name: "HealthLine Distributors Pvt. Ltd.", location: "Mumbai, Maharashtra", phone: "+91 98200 11223", email: "sales@healthlinedist.in" },
    delivery: { time: "2–4 business days", coverage: "Pan India (28 states)", shipping: "Free shipping on orders above ₹5,000" }
  },
  {
    id: "med-002",
    name: "Azithro 250 Capsules",
    brand: "Sun Pharma",
    category: "Capsules",
    strength: "250 mg",
    packSize: "3 x 6 Capsules",
    mrp: 110.0,
    retailerPrice: 84.0,
    distributorPrice: 72.5,
    gst: 12,
    moq: 30,
    stock: 180,
    stockStatus: "Low Stock",
    rating: 4.4,
    reviewCount: 198,
    mfgDate: "2025-01",
    expDate: "2027-12",
    dosageForm: "Oral Capsule",
    composition: ["Azithromycin IP 250 mg", "Excipients q.s."],
    uses: "Broad-spectrum antibiotic used to treat respiratory, throat and skin infections caused by bacteria.",
    benefits: ["Broad Spectrum", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Nausea", "Stomach upset", "Dizziness", "Diarrhoea"],
    storage: ["Store below 25°C", "Keep away from moisture", "Keep out of reach of children"],
    distributor: { name: "MediCore Supplies", location: "Ahmedabad, Gujarat", phone: "+91 99250 44556", email: "orders@medicore.co.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹120" }
  },
  {
    id: "med-003",
    name: "Cofdex Cough Syrup",
    brand: "Dr. Reddy's",
    category: "Syrups",
    strength: "100 ml",
    packSize: "1 x 100 ml Bottle",
    mrp: 95.0,
    retailerPrice: 70.0,
    distributorPrice: 61.0,
    gst: 5,
    moq: 24,
    stock: 0,
    stockStatus: "Out of Stock",
    rating: 4.1,
    reviewCount: 87,
    mfgDate: "2024-11",
    expDate: "2027-10",
    dosageForm: "Oral Syrup",
    composition: ["Dextromethorphan HBr 10 mg/5ml", "Chlorpheniramine Maleate 2 mg/5ml", "Flavoured base q.s."],
    uses: "Provides relief from dry cough, throat irritation and associated allergic symptoms.",
    benefits: ["Soothing Relief", "WHO-GMP Certified", "Sugar-free Variant", "Trusted Product"],
    sideEffects: ["Drowsiness", "Dry mouth", "Dizziness", "Nausea"],
    storage: ["Store below 25°C", "Do not freeze", "Keep out of reach of children"],
    distributor: { name: "Wellness Pharma Logistics", location: "Hyderabad, Telangana", phone: "+91 90000 77881", email: "support@wellnesspharma.in" },
    delivery: { time: "4–6 business days", coverage: "South & West India", shipping: "Free shipping on orders above ₹4,000" }
  },
  {
    id: "med-004",
    name: "Ceftri 1g Injection",
    brand: "Mankind",
    category: "Injections",
    strength: "1 g",
    packSize: "1 Vial + Diluent",
    mrp: 65.0,
    retailerPrice: 47.0,
    distributorPrice: 40.5,
    gst: 12,
    moq: 100,
    stock: 980,
    stockStatus: "In Stock",
    rating: 4.7,
    reviewCount: 256,
    mfgDate: "2025-02",
    expDate: "2027-08",
    dosageForm: "Injectable (IV/IM)",
    composition: ["Ceftriaxone Sodium IP eq. to Ceftriaxone 1 g", "Sterile water for injection q.s."],
    uses: "Third-generation cephalosporin antibiotic for serious bacterial infections including septicaemia.",
    benefits: ["Hospital Grade", "WHO-GMP Certified", "Sterile Manufacturing", "Trusted Product"],
    sideEffects: ["Injection site pain", "Nausea", "Headache", "Dizziness"],
    storage: ["Store below 25°C", "Protect from light", "Keep out of reach of children"],
    distributor: { name: "Apex Critical Care", location: "Delhi NCR", phone: "+91 98110 33445", email: "procure@apexcare.in" },
    delivery: { time: "2–3 business days", coverage: "Pan India", shipping: "Cold-chain assured · Free above ₹10,000" }
  },
  {
    id: "med-005",
    name: "Mupiro Skin Ointment",
    brand: "Glenmark",
    category: "Ointments",
    strength: "2% w/w",
    packSize: "1 x 10 g Tube",
    mrp: 88.0,
    retailerPrice: 64.0,
    distributorPrice: 55.0,
    gst: 12,
    moq: 40,
    stock: 320,
    stockStatus: "In Stock",
    rating: 4.3,
    reviewCount: 142,
    mfgDate: "2025-04",
    expDate: "2028-03",
    dosageForm: "Topical Ointment",
    composition: ["Mupirocin IP 2% w/w", "Polyethylene glycol base q.s."],
    uses: "Topical antibiotic for skin infections such as impetigo and infected wounds.",
    benefits: ["Fast Acting", "WHO-GMP Certified", "Dermatologist Tested", "Trusted Product"],
    sideEffects: ["Burning sensation", "Itching", "Redness", "Dryness"],
    storage: ["Store below 25°C", "Keep cap tightly closed", "Keep out of reach of children"],
    distributor: { name: "DermaTrade Distributors", location: "Pune, Maharashtra", phone: "+91 98220 66778", email: "hello@dermatrade.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹90" }
  },
  {
    id: "med-006",
    name: "Pantop 40 Tablets",
    brand: "Lupin",
    category: "Tablets",
    strength: "40 mg",
    packSize: "10 x 15 Tablets",
    mrp: 145.0,
    retailerPrice: 108.0,
    distributorPrice: 94.0,
    gst: 12,
    moq: 50,
    stock: 2600,
    stockStatus: "In Stock",
    rating: 4.5,
    reviewCount: 221,
    mfgDate: "2025-03",
    expDate: "2028-01",
    dosageForm: "Enteric-coated Tablet",
    composition: ["Pantoprazole Sodium IP eq. to Pantoprazole 40 mg", "Excipients q.s."],
    uses: "Reduces stomach acid; used for acidity, heartburn and gastro-oesophageal reflux disease (GERD).",
    benefits: ["Long Lasting", "WHO-GMP Certified", "Enteric Coated", "Trusted Product"],
    sideEffects: ["Headache", "Nausea", "Dizziness", "Flatulence"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "HealthLine Distributors Pvt. Ltd.", location: "Mumbai, Maharashtra", phone: "+91 98200 11223", email: "sales@healthlinedist.in" },
    delivery: { time: "2–4 business days", coverage: "Pan India", shipping: "Free shipping on orders above ₹5,000" }
  },
  {
    id: "med-007",
    name: "Amox 500 Capsules",
    brand: "Cipla",
    category: "Capsules",
    strength: "500 mg",
    packSize: "10 x 10 Capsules",
    mrp: 92.0,
    retailerPrice: 68.0,
    distributorPrice: 59.0,
    gst: 12,
    moq: 50,
    stock: 140,
    stockStatus: "Low Stock",
    rating: 4.2,
    reviewCount: 176,
    mfgDate: "2025-01",
    expDate: "2027-11",
    dosageForm: "Oral Capsule",
    composition: ["Amoxicillin Trihydrate IP eq. to Amoxicillin 500 mg", "Excipients q.s."],
    uses: "Penicillin antibiotic for ear, nose, throat, chest and urinary tract infections.",
    benefits: ["Broad Spectrum", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Nausea", "Diarrhoea", "Rash", "Headache"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "MediCore Supplies", location: "Ahmedabad, Gujarat", phone: "+91 99250 44556", email: "orders@medicore.co.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹120" }
  },
  {
    id: "med-008",
    name: "Ironvit Tonic Syrup",
    brand: "Zydus",
    category: "Syrups",
    strength: "200 ml",
    packSize: "1 x 200 ml Bottle",
    mrp: 165.0,
    retailerPrice: 122.0,
    distributorPrice: 106.0,
    gst: 18,
    moq: 24,
    stock: 540,
    stockStatus: "In Stock",
    rating: 4.0,
    reviewCount: 64,
    mfgDate: "2025-02",
    expDate: "2027-09",
    dosageForm: "Oral Syrup",
    composition: ["Ferrous Ascorbate 30 mg", "Folic Acid 550 mcg", "Vitamin B12 7.5 mcg", "Flavoured base q.s."],
    uses: "Iron and vitamin supplement for the prevention and treatment of iron-deficiency anaemia.",
    benefits: ["Better Absorption", "WHO-GMP Certified", "Pleasant Taste", "Trusted Product"],
    sideEffects: ["Constipation", "Nausea", "Dark stools", "Stomach upset"],
    storage: ["Store below 25°C", "Do not freeze", "Keep out of reach of children"],
    distributor: { name: "Wellness Pharma Logistics", location: "Hyderabad, Telangana", phone: "+91 90000 77881", email: "support@wellnesspharma.in" },
    delivery: { time: "4–6 business days", coverage: "South & West India", shipping: "Free shipping on orders above ₹4,000" }
  },
  {
    id: "med-009",
    name: "Diclo Pain Injection",
    brand: "Alkem",
    category: "Injections",
    strength: "75 mg/ml",
    packSize: "5 x 1 ml Ampoules",
    mrp: 42.0,
    retailerPrice: 30.0,
    distributorPrice: 26.0,
    gst: 12,
    moq: 100,
    stock: 0,
    stockStatus: "Out of Stock",
    rating: 4.4,
    reviewCount: 109,
    mfgDate: "2024-12",
    expDate: "2027-06",
    dosageForm: "Injectable (IM)",
    composition: ["Diclofenac Sodium IP 75 mg/ml", "Sterile vehicle q.s."],
    uses: "Anti-inflammatory injection for acute pain, post-operative pain and musculoskeletal disorders.",
    benefits: ["Rapid Onset", "WHO-GMP Certified", "Sterile Manufacturing", "Trusted Product"],
    sideEffects: ["Injection site pain", "Nausea", "Dizziness", "Headache"],
    storage: ["Store below 25°C", "Protect from light", "Keep out of reach of children"],
    distributor: { name: "Apex Critical Care", location: "Delhi NCR", phone: "+91 98110 33445", email: "procure@apexcare.in" },
    delivery: { time: "2–3 business days", coverage: "Pan India", shipping: "Free above ₹10,000" }
  },
  {
    id: "med-010",
    name: "Clobeta GM Ointment",
    brand: "Torrent",
    category: "Ointments",
    strength: "15 g",
    packSize: "1 x 15 g Tube",
    mrp: 76.0,
    retailerPrice: 55.0,
    distributorPrice: 48.0,
    gst: 12,
    moq: 40,
    stock: 410,
    stockStatus: "In Stock",
    rating: 4.2,
    reviewCount: 98,
    mfgDate: "2025-03",
    expDate: "2028-02",
    dosageForm: "Topical Ointment",
    composition: ["Clobetasol Propionate 0.05%", "Gentamicin 0.1%", "Miconazole Nitrate 2%"],
    uses: "Combination ointment for inflammatory skin conditions with bacterial and fungal infection.",
    benefits: ["Triple Action", "WHO-GMP Certified", "Dermatologist Tested", "Trusted Product"],
    sideEffects: ["Burning", "Itching", "Skin thinning", "Redness"],
    storage: ["Store below 25°C", "Keep cap tightly closed", "Keep out of reach of children"],
    distributor: { name: "DermaTrade Distributors", location: "Pune, Maharashtra", phone: "+91 98220 66778", email: "hello@dermatrade.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹90" }
  },
  {
    id: "med-011",
    name: "Metfor 500 Tablets",
    brand: "Sun Pharma",
    category: "Tablets",
    strength: "500 mg",
    packSize: "10 x 20 Tablets",
    mrp: 58.0,
    retailerPrice: 42.0,
    distributorPrice: 36.0,
    gst: 12,
    moq: 50,
    stock: 3100,
    stockStatus: "In Stock",
    rating: 4.5,
    reviewCount: 287,
    mfgDate: "2025-02",
    expDate: "2028-01",
    dosageForm: "Sustained-release Tablet",
    composition: ["Metformin Hydrochloride IP 500 mg", "Excipients q.s."],
    uses: "First-line oral anti-diabetic agent for the management of type-2 diabetes mellitus.",
    benefits: ["Sustained Release", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Nausea", "Diarrhoea", "Metallic taste", "Loss of appetite"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "MediCore Supplies", location: "Ahmedabad, Gujarat", phone: "+91 99250 44556", email: "orders@medicore.co.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹120" }
  },
  {
    id: "med-012",
    name: "Omepra 20 Capsules",
    brand: "Dr. Reddy's",
    category: "Capsules",
    strength: "20 mg",
    packSize: "10 x 10 Capsules",
    mrp: 78.0,
    retailerPrice: 57.0,
    distributorPrice: 49.0,
    gst: 12,
    moq: 50,
    stock: 95,
    stockStatus: "Low Stock",
    rating: 4.3,
    reviewCount: 154,
    mfgDate: "2025-01",
    expDate: "2027-12",
    dosageForm: "Delayed-release Capsule",
    composition: ["Omeprazole IP 20 mg (as enteric-coated pellets)", "Excipients q.s."],
    uses: "Proton-pump inhibitor for acid reflux, peptic ulcers and Zollinger-Ellison syndrome.",
    benefits: ["24h Acid Control", "WHO-GMP Certified", "Enteric Coated", "Trusted Product"],
    sideEffects: ["Headache", "Abdominal pain", "Nausea", "Flatulence"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "Wellness Pharma Logistics", location: "Hyderabad, Telangana", phone: "+91 90000 77881", email: "support@wellnesspharma.in" },
    delivery: { time: "4–6 business days", coverage: "South & West India", shipping: "Free shipping above ₹4,000" }
  },
  {
    id: "med-013",
    name: "Ondem Relief Syrup",
    brand: "Abbott",
    category: "Syrups",
    strength: "30 ml",
    packSize: "1 x 30 ml Bottle",
    mrp: 56.0,
    retailerPrice: 41.0,
    distributorPrice: 35.0,
    gst: 5,
    moq: 24,
    stock: 720,
    stockStatus: "In Stock",
    rating: 4.1,
    reviewCount: 73,
    mfgDate: "2025-03",
    expDate: "2027-10",
    dosageForm: "Oral Syrup",
    composition: ["Ondansetron IP 2 mg/5ml", "Flavoured base q.s."],
    uses: "Anti-emetic syrup used to prevent nausea and vomiting in children and adults.",
    benefits: ["Quick Relief", "WHO-GMP Certified", "Child Friendly", "Trusted Product"],
    sideEffects: ["Headache", "Constipation", "Drowsiness", "Dizziness"],
    storage: ["Store below 25°C", "Do not freeze", "Keep out of reach of children"],
    distributor: { name: "Wellness Pharma Logistics", location: "Hyderabad, Telangana", phone: "+91 90000 77881", email: "support@wellnesspharma.in" },
    delivery: { time: "4–6 business days", coverage: "South & West India", shipping: "Standard shipping ₹90" }
  },
  {
    id: "med-014",
    name: "Vitcobal B12 Injection",
    brand: "Zydus",
    category: "Injections",
    strength: "1000 mcg/ml",
    packSize: "5 x 1 ml Ampoules",
    mrp: 120.0,
    retailerPrice: 89.0,
    distributorPrice: 77.0,
    gst: 12,
    moq: 50,
    stock: 260,
    stockStatus: "In Stock",
    rating: 4.6,
    reviewCount: 131,
    mfgDate: "2025-02",
    expDate: "2027-09",
    dosageForm: "Injectable (IM)",
    composition: ["Methylcobalamin 1000 mcg/ml", "Sterile vehicle q.s."],
    uses: "Vitamin B12 supplement for nerve health, anaemia and peripheral neuropathy.",
    benefits: ["Nerve Support", "WHO-GMP Certified", "Sterile Manufacturing", "Trusted Product"],
    sideEffects: ["Injection site pain", "Nausea", "Headache", "Itching"],
    storage: ["Store below 25°C", "Protect from light", "Keep out of reach of children"],
    distributor: { name: "Apex Critical Care", location: "Delhi NCR", phone: "+91 98110 33445", email: "procure@apexcare.in" },
    delivery: { time: "2–3 business days", coverage: "Pan India", shipping: "Free above ₹10,000" }
  },
  {
    id: "med-015",
    name: "Calcimax Bone Tablets",
    brand: "Mankind",
    category: "Tablets",
    strength: "500 mg + D3",
    packSize: "10 x 15 Tablets",
    mrp: 135.0,
    retailerPrice: 99.0,
    distributorPrice: 86.0,
    gst: 18,
    moq: 50,
    stock: 1850,
    stockStatus: "In Stock",
    rating: 4.4,
    reviewCount: 203,
    mfgDate: "2025-03",
    expDate: "2028-02",
    dosageForm: "Film-coated Tablet",
    composition: ["Calcium Carbonate eq. to elemental Calcium 500 mg", "Vitamin D3 250 IU", "Excipients q.s."],
    uses: "Calcium and vitamin D3 supplement for bone health and the prevention of osteoporosis.",
    benefits: ["Stronger Bones", "WHO-GMP Certified", "Better Absorption", "Trusted Product"],
    sideEffects: ["Constipation", "Bloating", "Nausea", "Gas"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "HealthLine Distributors Pvt. Ltd.", location: "Mumbai, Maharashtra", phone: "+91 98200 11223", email: "sales@healthlinedist.in" },
    delivery: { time: "2–4 business days", coverage: "Pan India", shipping: "Free shipping above ₹5,000" }
  },
  {
    id: "med-016",
    name: "Levoflox 500 Tablets",
    brand: "Lupin",
    category: "Tablets",
    strength: "500 mg",
    packSize: "10 x 5 Tablets",
    mrp: 168.0,
    retailerPrice: 124.0,
    distributorPrice: 108.0,
    gst: 12,
    moq: 50,
    stock: 75,
    stockStatus: "Low Stock",
    rating: 4.3,
    reviewCount: 118,
    mfgDate: "2025-01",
    expDate: "2027-11",
    dosageForm: "Film-coated Tablet",
    composition: ["Levofloxacin Hemihydrate IP eq. to Levofloxacin 500 mg", "Excipients q.s."],
    uses: "Fluoroquinolone antibiotic for respiratory, urinary and skin infections.",
    benefits: ["Once Daily", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Nausea", "Dizziness", "Insomnia", "Headache"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "MediCore Supplies", location: "Ahmedabad, Gujarat", phone: "+91 99250 44556", email: "orders@medicore.co.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹120" }
  },
  {
    id: "med-017",
    name: "Cetiriz 10 Tablets",
    brand: "Glenmark",
    category: "Tablets",
    strength: "10 mg",
    packSize: "10 x 10 Tablets",
    mrp: 34.0,
    retailerPrice: 24.0,
    distributorPrice: 20.5,
    gst: 12,
    moq: 50,
    stock: 2950,
    stockStatus: "In Stock",
    rating: 4.5,
    reviewCount: 246,
    mfgDate: "2025-04",
    expDate: "2028-03",
    dosageForm: "Film-coated Tablet",
    composition: ["Cetirizine Hydrochloride IP 10 mg", "Excipients q.s."],
    uses: "Anti-histamine for allergic rhinitis, urticaria, sneezing and watery eyes.",
    benefits: ["Non-drowsy*", "WHO-GMP Certified", "Fast Acting", "Trusted Product"],
    sideEffects: ["Mild drowsiness", "Dry mouth", "Headache", "Fatigue"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "DermaTrade Distributors", location: "Pune, Maharashtra", phone: "+91 98220 66778", email: "hello@dermatrade.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹90" }
  },
  {
    id: "med-018",
    name: "Gabapen 300 Capsules",
    brand: "Torrent",
    category: "Capsules",
    strength: "300 mg",
    packSize: "10 x 10 Capsules",
    mrp: 198.0,
    retailerPrice: 146.0,
    distributorPrice: 127.0,
    gst: 12,
    moq: 30,
    stock: 0,
    stockStatus: "Out of Stock",
    rating: 4.2,
    reviewCount: 89,
    mfgDate: "2024-12",
    expDate: "2027-07",
    dosageForm: "Oral Capsule",
    composition: ["Gabapentin IP 300 mg", "Excipients q.s."],
    uses: "Used for neuropathic pain and as an adjunct in the treatment of partial seizures.",
    benefits: ["Nerve Pain Relief", "WHO-GMP Certified", "High Quality Manufacturing", "Trusted Product"],
    sideEffects: ["Drowsiness", "Dizziness", "Fatigue", "Swelling"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep out of reach of children"],
    distributor: { name: "Apex Critical Care", location: "Delhi NCR", phone: "+91 98110 33445", email: "procure@apexcare.in" },
    delivery: { time: "2–3 business days", coverage: "Pan India", shipping: "Free above ₹10,000" }
  },
  {
    id: "med-019",
    name: "Soothe Probiotic Syrup",
    brand: "Abbott",
    category: "Syrups",
    strength: "60 ml",
    packSize: "1 x 60 ml Bottle",
    mrp: 142.0,
    retailerPrice: 105.0,
    distributorPrice: 91.0,
    gst: 18,
    moq: 24,
    stock: 480,
    stockStatus: "In Stock",
    rating: 4.0,
    reviewCount: 58,
    mfgDate: "2025-02",
    expDate: "2027-08",
    dosageForm: "Oral Suspension",
    composition: ["Lactobacillus + Bifidobacterium blend 2 billion CFU/5ml", "Prebiotic base q.s."],
    uses: "Probiotic supplement to restore gut flora during and after antibiotic therapy and diarrhoea.",
    benefits: ["Gut Health", "WHO-GMP Certified", "Child Friendly", "Trusted Product"],
    sideEffects: ["Mild bloating", "Gas", "Stomach upset", "Nausea"],
    storage: ["Store below 25°C", "Refrigerate after opening", "Keep out of reach of children"],
    distributor: { name: "Wellness Pharma Logistics", location: "Hyderabad, Telangana", phone: "+91 90000 77881", email: "support@wellnesspharma.in" },
    delivery: { time: "4–6 business days", coverage: "South & West India", shipping: "Cold-chain assured" }
  },
  {
    id: "med-020",
    name: "Betadex Wound Ointment",
    brand: "Alkem",
    category: "Ointments",
    strength: "20 g",
    packSize: "1 x 20 g Tube",
    mrp: 64.0,
    retailerPrice: 46.0,
    distributorPrice: 39.5,
    gst: 12,
    moq: 40,
    stock: 360,
    stockStatus: "In Stock",
    rating: 4.4,
    reviewCount: 121,
    mfgDate: "2025-03",
    expDate: "2028-01",
    dosageForm: "Topical Ointment",
    composition: ["Povidone-Iodine IP 5% w/w", "Ointment base q.s."],
    uses: "Antiseptic ointment for minor cuts, burns, abrasions and prevention of wound infection.",
    benefits: ["Antiseptic Action", "WHO-GMP Certified", "Fast Healing", "Trusted Product"],
    sideEffects: ["Local irritation", "Redness", "Itching", "Dryness"],
    storage: ["Store below 25°C", "Keep cap tightly closed", "Keep out of reach of children"],
    distributor: { name: "DermaTrade Distributors", location: "Pune, Maharashtra", phone: "+91 98220 66778", email: "hello@dermatrade.in" },
    delivery: { time: "3–5 business days", coverage: "Pan India", shipping: "Standard shipping ₹90" }
  }
];

/* ---------------------------------------------------------------------
   Shared customer reviews & FAQs (reused on the details page).
   In production these would live in their own collections, fetched per
   product id. Kept generic here for demo realism.
   --------------------------------------------------------------------- */
const SAMPLE_REVIEWS = [
  { name: "Rajesh Medical Stores", rating: 5, date: "2026-05-12", text: "Consistent quality and fast dispatch. We reorder this every month for our pharmacy chain." },
  { name: "Sunrise Distributors", rating: 4, date: "2026-04-28", text: "Good margins for retailers and packaging is tamper-proof. Delivery could be a day quicker." },
  { name: "Apollo Franchise Outlet", rating: 5, date: "2026-04-03", text: "Genuine product with proper batch documentation. COA was provided without asking." },
  { name: "City Care Chemist", rating: 4, date: "2026-03-19", text: "Reliable supplier. The bulk pricing on MOQ orders is competitive." },
  { name: "Wellness Pharmacy", rating: 3, date: "2026-02-22", text: "Product is fine but one carton arrived with a dented box. Replaced quickly though." }
];

const SAMPLE_FAQS = [
  { q: "What is this medicine used for?", a: "It is indicated for the conditions listed in the “Uses” section above. Always dispense as per a registered medical practitioner's prescription." },
  { q: "What is the recommended dosage?", a: "Dosage depends on the patient's age, weight and condition. Follow the prescribing physician's instructions and the enclosed package insert." },
  { q: "Are there any side effects?", a: "Common side effects are listed in the “Side Effects” section. Most are mild and transient. Report severe reactions to a physician immediately." },
  { q: "Is bulk ordering available?", a: "Yes. This product is available for bulk B2B procurement above the listed Minimum Order Quantity (MOQ) with tiered distributor pricing." }
];

const RETURN_POLICY = {
  eligibility: "Returns are accepted for damaged, expired, or incorrectly shipped consignments. Temperature-sensitive items are non-returnable once the cold chain is broken.",
  conditions: "Items must be unopened, in original tamper-proof packaging, with the batch number and invoice intact. Refunds are processed to the original payment method after QA verification.",
  window: "Raise a return request within 7 days of delivery via your B2B account dashboard."
};

/* ---------------------------------------------------------------------
   Accessor functions — the ONLY way the UI reads data.
   Swap the bodies for fetch() calls to connect a real backend.
   --------------------------------------------------------------------- */
function getAllProducts() {
  return PRODUCTS;
}

function getProductById(id) {
  return PRODUCTS.find(function (p) { return p.id === id; }) || null;
}

/* Returns up to `limit` related products: same category or same brand,
   excluding the current product. */
function getRelatedProducts(product, limit) {
  limit = limit || 8;
  return PRODUCTS
    .filter(function (p) {
      return p.id !== product.id &&
        (p.category === product.category || p.brand === product.brand);
    })
    .slice(0, limit);
}

/* Unique, sorted brand list — used to build the brand filter dynamically. */
function getAllBrands() {
  var set = {};
  PRODUCTS.forEach(function (p) { set[p.brand] = true; });
  return Object.keys(set).sort();
}